spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=web;encrypt=true;trustServerCertificate=true
    username: sa
    password: 11122003tpt

  devtools:
    restart:
      poll-interval: 1s


  jpa:
    show-sql: true
    #    generate-ddl: true
    #    properties:
    #      hibernate:
    #        hbm2ddl:
    #          auto: update
    hibernate:
      ddl-auto:none

# Mail
mailServer:
  host: smtp.gmail.com
  port: 587
  email: hoangtuananh1772003@gmail.com
  password: vligdsqcyeaqlcex
  protocol: smtp
  isSSL: false

# Swagger3
config:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://familytree-api.com

springdoc:
  swagger-ui:
    path: /familytree-documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
  api-docs:
    path: /familytree-api-docs
  packages-to-scan: com.example.familytree.controllers




